version: '3.7'

services: # the different images that will be running as containers
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod

  web: # service name

    #build the image for the web service from the dockerfile in parent directory.  
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn webscrapper_api.wsgi:application --bind 0.0.0.0:8000
    
    # map data and files from parent directory in host to api directory in docker container
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
